variable "failover_subnet_name" {
  type        = string
  description = "The name of the failover subnet. Used in the Power Platform Enterprise Policy network connection."
}

variable "failover_vnet_name" {
  type        = string
  description = "The name of the failover Virtual Network to be used in connecting Power Platform to Azure. Note that failover networks are required for Power Platform's enterprise policy connection."
}



variable "power_platform_environment" {
  type = object({
    name              = string
    id                = string # Optional. If provided, the module will attempt to use the existing environment. If left blank, a new environment will be created.
    language_code     = number
    currency_code     = string
    security_group_id = string
    environment_type  = string
    location          = string
  })
  description = <<DESCRIPTION
  - `name`: The name of the Power Platform environment to be managed.
  - `language_code`: The language code for the Power Platform environment.
  - `currency_code`: The currency code for the Power Platform environment.
  - `security_group_id`: The ID of the security group to be used for initial access to the Power Platform environment.
  - `environment_type`: The type of the Power Platform environment to be managed.
DESCRIPTION
}

variable "power_platform_managed_environment" {
  type = object({
    id                         = string # Optional. If provided, the module will attempt to use the existing managed environment. If left blank, a new environment will be created.
    is_usage_insights_disabled = bool
    is_group_sharing_disabled  = bool
    limit_sharing_mode         = string
    max_limit_user_sharing     = number
    solution_checker_mode      = string
    suppress_validation_emails = bool
    maker_onboarding_markdown  = string
    maker_onboarding_url       = string
  })
  description = <<DESCRIPTION
  - `is_usage_insights_disabled`: Whether usage insights are disabled for the Power Platform managed environment.
  - `is_group_sharing_disabled`: Whether group sharing is disabled for the Power Platform managed environment.
  - `limit_sharing_mode`: The sharing mode for the Power Platform managed environment.
  - `max_limit_user_sharing`: The maximum limit for user sharing in the Power Platform managed environment.
  - `solution_checker_mode`: The solution checker mode for the Power Platform managed environment.
  - `suppress_validation_emails`: Whether validation emails are suppressed for the Power Platform managed environment.
  - `maker_onboarding_markdown`: The onboarding markdown for makers in the Power Platform managed environment.
  - `maker_onboarding_url`: The onboarding URL for makers in the Power Platform managed environment.
DESCRIPTION
}

variable "primary_subnet_name" {
  type        = string
  description = "The name of the primary subnet. Used in the Power Platform Enterprise Policy network connection."
}

variable "primary_vnet_name" {
  type        = string
  description = "The name of the primary Virtual Network to be used in connecting Power Platform to Azure"
}

# required for AVM interface
variable "resource_group_name" {
  type        = string
  description = "The name of the resource group to create this module's resources in"
}

variable "unique_id" {
  type        = string
  description = "The unique ID to include with any resources generated by this module"
}

# tflint-ignore: terraform_unused_declarations
variable "customer_managed_key" {
  type = object({
    key_vault_resource_id = string
    key_name              = string
    key_version           = optional(string, null)
    user_assigned_identity = optional(object({
      resource_id = string
    }), null)
  })
  default     = null
  description = <<DESCRIPTION
Customer-managed key encryption is not applicable for this module.

A map describing customer-managed keys to associate with the resource. This includes the following properties:
- `key_vault_resource_id` - The resource ID of the Key Vault where the key is stored.
- `key_name` - The name of the key.
- `key_version` - (Optional) The version of the key. If not specified, the latest version is used.
- `user_assigned_identity` - (Optional) An object representing a user-assigned identity with the following properties:
  - `resource_id` - The resource ID of the user-assigned identity.
DESCRIPTION  
}


variable "resource_share_user" {
  type        = map(string)
  default     = {}
  description = "A map of user identifiers to object IDs of interactive users to share the managed resources with. This is used to share resource visibility after a service principal creates resources. If no value is specified, only the service principal will have visibility into the resources."
}


# required for AVM interface
variable "tags" {
  type        = map(string)
  default     = null
  description = "(Optional) Tags of the resource."
}

variable "pp_environment_user_Security_role" {
  description = "Power Platform environment user security role, examples of roles can be: System Administrator, System Customizer, basic user and many more."
  type        = list(string)
  default     = ["Basic User", "Bot Author"]
}
